"""
Optional disk mirror of peer prompt events.

When ``spec watch --mirror`` is set, every incoming :class:`IncomingEvent`
is appended to ``prompts/captured/peers/<handle>/<branch>.prompts`` in a
deliberately simple, append-only TOML-ish format. These files are a
local cache of teammate activity — never touched by ``spec push``,
gitignored by default, and safe to delete at any time.

Why a separate format from the canonical ``.prompts`` schema:

* The wire format is one event = one turn, not one session. Building a
  fully-spec'd `.prompts` file would require buffering until the
  session ends, which never reliably happens for peers.
* The mirror is *advisory* — the user reads it locally to learn what
  teammates are working on. They review and curate their own
  ``.prompts`` files via the existing capture / submit / review flow.
* Formal `.prompts` schema rejects unknown keys (good for governance,
  bad for fast-moving telemetry). The mirror file is friendlier to
  forward-compat additions.

The file is human-greppable and looks like:

    # Spec Live mirror — peer @alice
    # Auto-generated by `spec watch --mirror`. Local cache only.

    [[turn]]
    id = 41827
    at = "2026-05-08T12:34:56Z"
    branch = "feature/billing-rewrite"
    role = "user"
    title = "Make /login retry on 5xx"
    summary = "First sentence preview…"
    text = '''
    Full prompt body if available.
    '''
    paths = ["spec/auth.md"]
"""
from __future__ import annotations

import logging
import re
import threading
from datetime import datetime, timezone
from pathlib import Path

from .events import IncomingEvent

log = logging.getLogger(__name__)

PEERS_DIRNAME = "peers"


def _branch_slug(branch: str | None) -> str:
    if not branch:
        return "no-branch"
    s = branch.lower().strip()
    s = re.sub(r"[^a-z0-9._-]+", "-", s)
    s = s.strip("-._") or "branch"
    return s[:128]


def _safe_handle(handle: str | None, fallback: str = "unknown") -> str:
    if not handle:
        return fallback
    s = handle.lower().strip()
    s = re.sub(r"[^a-z0-9._-]+", "-", s)
    return s.strip("-._") or fallback


def _toml_string(value: str | None, *, multiline: bool = False) -> str:
    """Tiny TOML string emitter for the mirror file.

    Not a full TOML serializer — we only need the two shapes the
    mirror uses (single-line keys and multiline ``text`` blocks). The
    canonical writer for actual ``.prompts`` files lives in
    ``spec_cli.prompts.render``; using it here would buy us nothing
    and pull in rendering rules that don't apply.
    """
    if value is None:
        return '""'
    if multiline:
        # Triple-single-quoted strings are TOML literal strings —
        # they don't process escapes, which is exactly what we want
        # for raw prompt content. The only forbidden sequence is
        # ``'''`` itself; we escape that as ``''\\'''`` (TOML's escape
        # for an embedded literal triple-quote).
        safe = value.replace("'''", "''\\'''")
        return f"'''\n{safe}\n'''"
    # Single-line basic string — escape backslashes and double-quotes.
    safe = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ")
    return f'"{safe}"'


def _format_paths(paths: list[str]) -> str:
    if not paths:
        return "[]"
    inner = ", ".join(_toml_string(p) for p in paths)
    return f"[{inner}]"


class PeerMirror:
    """Append-only writer for peer event mirrors.

    One file per ``(peer-handle, branch-slug)`` tuple. We do *not*
    deduplicate by event id at write time — duplicates are rare
    (only on reconnect within the same daemon run) and the file is
    advisory. If we ever need dedup, a sidecar ``.idx`` storing the
    last id per file would do it without scanning the body.
    """

    def __init__(self, bundle_root: Path) -> None:
        self._root = bundle_root / "prompts" / "captured" / PEERS_DIRNAME
        self._lock = threading.Lock()

    def write_event(self, event: IncomingEvent) -> Path | None:
        try:
            handle = _safe_handle(event.author_handle, fallback=str(event.author_user_id))
            branch_slug = _branch_slug(event.branch)
            target_dir = self._root / handle
            target_dir.mkdir(parents=True, exist_ok=True)
            target = target_dir / f"{branch_slug}.prompts"
            block = self._render_block(event)
            with self._lock:
                # Initialize header on first write.
                if not target.exists():
                    target.write_text(self._header(event), encoding="utf-8")
                with target.open("a", encoding="utf-8") as f:
                    f.write(block)
            return target
        except OSError as e:
            log.info("spec-live: mirror write failed: %s", e)
            return None

    # ── internals -----------------------------------------------------

    @staticmethod
    def _header(event: IncomingEvent) -> str:
        return (
            f"# Spec Live mirror — peer {event.author_display}\n"
            "# Auto-generated by `spec watch --mirror`.\n"
            "# Local cache only — never pushed, gitignored by default.\n"
            f"# Created: {datetime.now(timezone.utc).isoformat()}\n\n"
        )

    @staticmethod
    def _render_block(event: IncomingEvent) -> str:
        lines: list[str] = []
        lines.append("[[turn]]")
        lines.append(f"id = {event.id}")
        if event.turn_at is not None:
            lines.append(f"at = {_toml_string(event.turn_at.isoformat())}")
        else:
            lines.append(f"at = {_toml_string(event.received_at.isoformat())}")
        lines.append(f"received_at = {_toml_string(event.received_at.isoformat())}")
        lines.append(f"role = {_toml_string(event.role)}")
        lines.append(f"source = {_toml_string(event.source)}")
        if event.session_id:
            lines.append(f"session_id = {_toml_string(event.session_id)}")
        if event.branch:
            lines.append(f"branch = {_toml_string(event.branch)}")
        if event.commit_sha:
            lines.append(f"commit_sha = {_toml_string(event.commit_sha)}")
        if event.model:
            lines.append(f"model = {_toml_string(event.model)}")
        if event.title:
            lines.append(f"title = {_toml_string(event.title)}")
        if event.summary:
            lines.append(f"summary = {_toml_string(event.summary)}")
        if event.text:
            lines.append(f"text = {_toml_string(event.text, multiline=True)}")
        if event.paths_touched:
            lines.append(f"paths = {_format_paths(event.paths_touched)}")
        return "\n".join(lines) + "\n\n"


__all__ = ["PeerMirror"]
