"""Human-readable mirror of team editing state for agents and humans.

``.spec/team-editing-brief.md`` is regenerated whenever
``.spec/team-presence.json`` changes. IDEs and rules can point models at
this file without parsing JSON.

``mirror_stale`` answers whether ``team-presence.json`` is too old to
trust for coordination (``spec watch`` likely not running).
"""
from __future__ import annotations

import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

TEAM_EDITING_BRIEF_FILENAME = "team-editing-brief.md"
# If ``updated_at`` on the JSON is older than this, ``spec locks check``
# treats the mirror as stale and fails open (exit 0).
DEFAULT_LOCKS_MIRROR_STALE_SECS = 900.0


def _parse_iso_utc(raw: Any) -> datetime | None:
    if not raw or not isinstance(raw, str):
        return None
    s = raw.strip().replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(s).astimezone(timezone.utc)
    except ValueError:
        return None


def team_presence_mirror_stale(
    body: dict[str, Any] | None, *, max_age_secs: float = DEFAULT_LOCKS_MIRROR_STALE_SECS
) -> bool:
    """True when the mirror should not be trusted for edit coordination.

    Missing body, missing ``updated_at``, unparseable timestamps, or
    ``updated_at`` older than ``max_age_secs`` → stale.
    """
    if not body:
        return True
    ts = _parse_iso_utc(body.get("updated_at"))
    if ts is None:
        return True
    age = (datetime.now(timezone.utc) - ts).total_seconds()
    return age > max_age_secs


def render_team_editing_brief(body: dict[str, Any]) -> str:
    """Markdown summary derived from the same dict written to
    ``team-presence.json``."""
    lines: list[str] = [
        "# Spec Live — team editing (auto-generated)",
        "",
        "Regenerated by `spec watch` when `.spec/team-presence.json` changes.",
        "Read this (or run `spec locks check <path>`) before editing files",
        "other teammates may be touching.",
        "",
    ]
    updated = body.get("updated_at")
    if isinstance(updated, str) and updated:
        lines.append(f"**Mirror updated:** {updated} (UTC)")
        lines.append("")

    members = body.get("members") or []
    if not isinstance(members, list):
        members = []

    if not members:
        lines.append("*No teammates currently listed in the live presence mirror.*")
        lines.append("")
        return "\n".join(lines) + "\n"

    lines.append("## Teammates with dirty files")
    lines.append("")
    for m in members:
        if not isinstance(m, dict):
            continue
        handle = m.get("handle") or m.get("name") or "(unknown)"
        branch = m.get("branch") or "?"
        last_seen = m.get("last_seen") or ""
        files = m.get("files") or []
        if not isinstance(files, list):
            files = []
        lines.append(f"### @{handle} · {branch} · last seen {last_seen}")
        if not files:
            lines.append("- _(clean)_")
        else:
            for f in files:
                if not isinstance(f, dict):
                    continue
                path = f.get("path") or "?"
                added = int(f.get("lines_added") or 0)
                removed = int(f.get("lines_removed") or 0)
                tag = " **new**" if f.get("untracked") else ""
                # Shorthand: path (+/-) — easy to grep.
                lines.append(f"- `{path}` (+{added}/-{removed}){tag}")
        lines.append("")

    lines.append("## Shorthand index")
    lines.append("")
    files_index = body.get("files_index")
    if isinstance(files_index, dict) and files_index:
        for path in sorted(files_index.keys()):
            entries = files_index.get(path)
            if not isinstance(entries, list):
                continue
            bits = []
            for e in entries:
                if not isinstance(e, dict):
                    continue
                if e.get("self"):
                    bits.append("you")
                    continue
                h = e.get("handle") or e.get("name") or "?"
                bits.append(f"@{h}")
            lines.append(f"- `{path}` → {', '.join(bits)}")
    else:
        lines.append("_Empty._")
    lines.append("")
    return "\n".join(lines) + "\n"


def write_team_editing_brief(bundle_root: Path, body: dict[str, Any]) -> bool:
    """Write ``.spec/team-editing-brief.md`` next to ``team-presence.json``.

    Atomic replace on success. Returns ``True`` if the file changed.
    """
    spec_dir = bundle_root / ".spec"
    target = spec_dir / TEAM_EDITING_BRIEF_FILENAME
    text = render_team_editing_brief(body)
    try:
        spec_dir.mkdir(parents=True, exist_ok=True)
        tmp_fd, tmp_name = tempfile.mkstemp(
            prefix=f"{TEAM_EDITING_BRIEF_FILENAME}.",
            suffix=".tmp",
            dir=str(spec_dir),
        )
        try:
            with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
                f.write(text)
                f.flush()
                try:
                    os.fsync(f.fileno())
                except OSError:
                    pass
            os.replace(tmp_name, target)
        except OSError:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise
    except OSError:
        return False

    return True


__all__ = [
    "DEFAULT_LOCKS_MIRROR_STALE_SECS",
    "TEAM_EDITING_BRIEF_FILENAME",
    "render_team_editing_brief",
    "team_presence_mirror_stale",
    "write_team_editing_brief",
]
